import { Hono } from "hono";
import { activityLogRoutes } from "./activity-logs.js";
import { adminIntakeRoutes } from "./admin-intake.js";
import { adminOpsRoutes } from "./admin-ops.js";
import { approvalRoutes } from "./approvals.js";
import { authRoutes } from "./auth.js";
import { contactRoutes } from "./contacts.js";
import { draftRoutes } from "./drafts.js";
import { emailSendRoutes } from "./email-sends.js";
import { healthRoutes } from "./health.js";
import { inboundMessageIntakeRoutes } from "./inbound-message-intake.js";
import { integrationRoutes } from "./integrations.js";
import { leadRoutes } from "./leads.js";
import { organizationRoutes } from "./organizations.js";
import { publicLeadRoutes } from "./public-leads.js";
import { taskRoutes } from "./tasks.js";
import { webhookRoutes } from "./webhooks/index.js";
import { workspaceApiKeyRoutes } from "./workspace-api-keys.js";

export const routes = new Hono();

routes.route("/", healthRoutes);
routes.route("/api", healthRoutes);
routes.route("/api/activity-logs", activityLogRoutes);
routes.route("/api/admin/intake", adminIntakeRoutes);
routes.route("/api/admin/ops", adminOpsRoutes);
routes.route("/api/approvals", approvalRoutes);
routes.route("/api/contacts", contactRoutes);
routes.route("/api/drafts", draftRoutes);
routes.route("/api/email-sends", emailSendRoutes);
routes.route("/api/intake", inboundMessageIntakeRoutes);
routes.route("/api/integrations", integrationRoutes);
routes.route("/api/leads", leadRoutes);
routes.route("/api/organizations", organizationRoutes);
routes.route("/api/public/leads", publicLeadRoutes);
routes.route("/api/tasks", taskRoutes);
routes.route("/api/webhooks", webhookRoutes);
routes.route("/api/workspace-api-keys", workspaceApiKeyRoutes);
routes.route("/auth", authRoutes);
